### ISSUE TITLE
The compiled version does not exist.

### ISSUE THREAD

**Issue by gburiticato** [hashicorp/vault-plugin-database-couchbase#8]
https://github.com/hashicorp/vault-plugin-database-couchbase#build

https://releases.hashicorp.com/vault-plugin-database-couchbase/ is returning 404

if you go to https://releases.hashicorp.com the directory does not exist.

403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: CCECADBAAD5ADD2A
HostId: LykPgvClBpWTl6OKuiMkcScb1bYwrW1XcaTJ+3jJgaZHACjD5MVDURQ58LfGstNA7f9OgpPRkYY=

**Comment by tomhjp** [comment]
Hey @gburiticato, thanks for your interest and for flagging this. There aren't actually any pre-built binaries available, so I've updated the readme accordingly.

From 1.6, this plugin should be bundled with the main Vault binary, but the instructions in the readme should work for building and registering it with Vault manually if you'd like to try it out before then. Feel free to open another issue if you do run into further problems though.
